version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  pythonapp:
    build: ./webapp
    ports:
      - "9092:9092"
    