# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    dc: sre1

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # Here it's Prometheus itself.
  - job_name: 'prometheus'   
    static_configs:
    - targets: ['localhost:9090']
  
  # Sample app
  - job_name: 'pythonapp'   
    static_configs:
    - targets: ['pythonapp:9092']
    